### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by peterbecich**
Travis CI coverage.  Closely copied from Helm: https://github.com/emacs-helm/helm/blob/master/.travis.yml

Succeeds: https://travis-ci.org/peterbecich/diredfl/builds/629573243

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Unsure what your goal was here, since there are no tests to run.

It's worth testing for clean byte-compilation, and package-lint compliance, though, so I've added a CI build separately to do that using github Actions and my [`setup-emacs`](https://github.com/purcell/setup-emacs) action.

**Comment by purcell** [comment]
Note that I don't use `evm` these days anyway, since I wrote [nix-emacs-ci](https://travis-ci.com/purcell/nix-emacs-ci) to do the job of evm more seamlessly in Travis, Actions and local environments. (`evm` is still a little faster to perform installation, though.)

**Comment by purcell** [comment]
Sorry, that link should have been https://github.com/purcell/nix-emacs-ci :-)

**Comment by peterbecich** [comment]
Thank you!  This information helps me.

**Comment by purcell** [comment]
It's worth noting that often `nix-emacs-ci` is slower than EVM, since installation can take up to a minute (in Travis), but it's very reliable and consistent, and that's ultimately my preference. And it's also convenient to be able to use `nix` to install any other CI dependencies.

**Pull request closed without merging**
